### ISSUE TITLE
tweaks made when integrating GE list with my own

### ISSUE THREAD

**Issue by jtauber** [dcthree/ancient-greek-lexica#70]
In case it's useful, here are the changes I made to your GE file when integrating it with my own:

https://github.com/greek-learner-texts/vocabulary-data/commit/b189eb8146afd3606a304fae893c03ab8a3ee8ed#diff-2e0b1434b221d2156f598cc1b9976828

Some of these may be valid corrections you want to make.

**Comment by ryanfb** [comment]
Thanks! I could probably also stand to re-run the scraper, to see if some fixes/additions have been made upstream.

**Comment by jtauber** [comment]
Yeah, there are ongoing additions from Words in Progress.
